service: shrouded

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  timeout: 30 # optional, in seconds, default is 6
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "ap-southeast-1"}
  tracing:
    lambda: true

functions:
  handleHelloWorld:
    handler: src/functionHandlers/helloWorld/index.handler
    events:
      - http:
          path: /hello
          method: get
          cors: true

custom:
  webpack:
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline
